# Prepare environment for building docker images
sudo: required

services:
  - docker

# setup environment for java
language: java

jdk:
  - openjdk12

env:
  - SONAR_HOST=https://sonar.ftk.de

# skip "mvn install -skipTexts=true" before building
install: true
#install:
#  - nvm install $NODE_VERSION

git:
  lfs_skip_smudge: true
  depth: false

script:
  # exit script when error occurs
  - set -e
  # prepare settings.xml: add nexus credentials from environment variables
  - cp .travis.settings.xml >$HOME/.m2/settings.xml
  # build all modules using maven
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar --batch-mode -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_TOKEN}
  # deploy to nexus repo
  - mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode

# Cache local maven repository to speed up build
# Remove packages from local maven repository before caching to avoid errors when refactoring maven structure
before_cache:
  - rm -rf $HOME/.m2/repository/io/sapl
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
