# Prepare environment for building docker images
sudo: required
services:
  - docker
# setup environment for java
language: java
jdk:
  - oraclejdk8
# skip "mvn install -skipTexts=true" before building
install: true
env:
  - SONAR_HOST=http://sonar.ftk.de:9000
script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - bash ./.travis.build.sh

# Cache local maven repository to speed up build
# Remove packages from local maven repository before caching to avoid errors when refactoring maven structure
before_cache:
  - rm -rf $HOME/.m2/repository/io/sapl
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
